apiVersion: v1
kind: Service
metadata:
  name: comicbox
  namespace: default
spec:
  selector:
    app: comicbox
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: comicbox
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: comicbox
      annotations:
            prometheus.io/scrape: "true"
            prometheus.io/path: 'swagger-stats/metrics'
            prometheus.io/port: "3000"
    spec:
      containers:
        - name: comicbox
          image: rivethead42/comicbox
          ports:
            - containerPort: 3000
